### ISSUE TITLE
Add additional information about preparing machine for running Sparkles guide

### ISSUE THREAD

**Issue by gscallon** [defenseunicorns/Sparkles-Guide#20]
Was just thinking about this from the perspective of less experienced Unicorns or less technical Unicorns. Wanted them to have some info in case they came across quick start commands and weren't sure about having npm/docker/podman installed on their machines.

I created a branch located here: https://github.com/defenseunicorns/Sparkles-Guide/tree/readme-update

I created a pull request here: https://github.com/defenseunicorns/Sparkles-Guide/pull/22

If this info is overkill (particularly the git clone section), I am happy to amend/remove it or feel free to add/change/remove anything.

**Comment by gscallon** [comment]
Syncing with Jordan or another Sparkles contributor on the PR component, will update

**Comment by gscallon** [comment]
PR is completed and ok to merge if desired.

**Comment by andrewsgreene** [comment]
Thanks @gscallon
